{% set version = "0.13.0" %}

package:
  name: scikit-image
  version: {{ version }}

source:
  fn: scikit-image-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/scikit-image/scikit-image-{{ version }}.tar.gz
  md5: c92b682ed77b568218423b7afe454996

build:
  number: 1

requirements:
  build:
    - setuptools
    - cython >=0.23
    - python
    - six >=1.4
    - numpy x.x
    - scipy >=0.17
  run:
    - python
    - six >=1.4
    - numpy >=1.11
    - scipy >=0.17
    - matplotlib >=1.1
    - networkx >=1.8
    - pillow >=1.7.8
    - dask >=0.5
    - PyWavelets >=0.4.0

test:
  imports:
    - skimage

about:
  home: http://scikit-image.org/
  license: BSD 3-Clause
  summary: Image processing routines for SciPy

extra:
  recipe-maintainers:
    - ivoflipse
    - jakirkham
    - jni
    - Korijn
    - msarahan
    - ocefpaf
