{% set version = "0.13.1" %}

package:
  name: scikit-image
  version: {{ version }}

source:
  git_url: https://github.com/scikit-image/scikit-image
  git_tag: v{{ version }}

build:
  number: 2
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - skivi = skimage.scripts.skivi:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.23
    - six >=1.7.3
    - numpy
    - scipy >=0.17
    - numpydoc >=0.6
    - msinttypes  # [win and py<35]
  run:
    - python
    - six >=1.7.3
    - {{ pin_compatible('numpy') }}
    - scipy >=0.17
    - matplotlib >=1.3.1
    - networkx >=1.8
    - pillow >=2.1.0
    - dask >=0.5
    - pywavelets >=0.4.0
    - imageio >=2.1.0

test:
  imports:
    - skimage

about:
  home: http://scikit-image.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Image processing routines for SciPy.'

extra:
  recipe-maintainers:
    - ivoflipse
    - jakirkham
    - jni
    - Korijn
    - mingwandroid
    - msarahan
    - ocefpaf
