{% set name = "scikit-image" %}
{% set version = "0.25.0" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/scikit-image/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7e7ec5cdac70f6df2dd6151cc27d4b8b6f2e029b4485b7635bb9522dc7023ddb
  patches:                     # [py<310]
    # Suppress the warning (pollutes CI) for py<310
    # because of RuntimeWarning: networkx backend defined more than once: nx-loopback,
    # see https://github.com/networkx/networkx/issues/7101 and https://github.com/python/importlib_metadata/pull/381/files
    - suppress_warnings.patch  # [py<310]

build:
  number: 0
  skip: true  # [py<310]
  entry_points:
    - skivi = skimage.scripts.skivi:main

requirements:
  build:
    # pythran code needs clang-cl on windows
    - clang                 # [win]
    - lld                   # [win]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - ninja
    - pkg-config
  host:
    - python
    - cython >=3.0.8
    - numpy 2
    - packaging
    - pip
    - pythran >=0.16
    - meson-python >=0.16
    - lazy_loader >=0.4
    - setuptools >=68
  run:
    - python
    - numpy >=1.24,<3
    - scipy >=1.11.2
    - networkx >=3.0
    - pillow >=10.1
    - imageio >=2.33,!=2.35.0
    - tifffile >=2022.8.12
    - packaging >=21
    - lazy_loader >=0.4
    - _openmp_mutex  # [linux]
  run_constrained:
    - matplotlib-base >=3.7
    - pooch >=1.6.0
    - pyamg >=5.2
    - astropy >=5.0
    - scikit-learn >=1.1
    - pywavelets >=1.6
    - scikit-learn >=1.2
    - cloudpickle >=0.2.1
    - dask-core >=2021.1.0,!=2024.8.0

{% set tests_to_skip = "_not_a_real_test" %}

# TODO: Report this upstream
# It seems that the apply_parallel tests can have relatively small errors,
# depending on underlying system; conda-forge has observed it on Windows, and
# Anaconda has observed it on Windows, macOS, and Linux.
{% set tests_to_skip = tests_to_skip + " or test_apply_parallel_rgb" %} # [osx and x86_64]

# https://github.com/scikit-image/scikit-image/issues/6865
{% set tests_to_skip = tests_to_skip + " or test_analytical_moments_calculation" %}

# https://github.com/scikit-image/scikit-image/issues/7061
{% set tests_to_skip = tests_to_skip + " or test_ellipse_parameter_stability" %}

# https://github.com/scikit-image/scikit-image/issues/6994
{% set tests_to_skip = tests_to_skip + " or test_imsave_roundtrip[shape1-uint16]" %}  # [linux and s390x]

# known to be broken on s390x: if platform.machine() == "s390x" and plugin == "pil" and fmt == "png"
{% set tests_to_skip = tests_to_skip + " or test_all_mono" %}          # [linux and s390x]

# Don't test thresholding funcs for Dask compatibility, 
# see https://github.com/scikit-image/scikit-image/pull/7509.
# Remove it with a new scikit-image release >=0.25.0.
{% set tests_to_skip = tests_to_skip + " or test_thresholds_dask_compatibility" %}

# see https://github.com/scipy/scipy/issues/20200 and https://github.com/scipy/scipy/issues/7408 
{% set tests_to_skip = tests_to_skip + " or test_2d_bf[float16] or test_2d_cg[float16] or test_2d_cg_mg[float16] or test_2d_cg_j[float16]" %}

# tifffile uses deprecated attribute `ndarray.newbyteorder` (for py313)
{% set tests_to_skip = tests_to_skip + " or test_kidney_3d_multichannel or test_lily_multichannel" %}  # [py>=313]

# AssertionError: Arrays are not almost equal to 7 decimals. Possible, it's a numpy compatibility issue
{% set tests_to_skip = tests_to_skip + " or test_are or test_rag_boundary" %}  # [osx and x86_64]

test:
  imports:
    - skimage
  source_files:
    - pyproject.toml
  requires:
    - pip
    - pooch >=1.6.0
    - asv
    - matplotlib-base
    - pywavelets
    - scikit-learn
    # TODO: Remove the selector when numpydoc and astropy will have py313 support on the main channel
    - numpydoc >=1.7  # [py<313]
    - astropy >=5.0   # [py<313]
    - pytest >=7.0
    - pytest-localserver
    - dask-core >=2021.1.0
  commands:
    - pip check
    - python -c "import skimage; print(skimage.__version__)"
    - set OPENBLAS_NUM_THREADS=1          # [win]
    - set OMP_NUM_THREADS=1               # [win]
    - export OPENBLAS_NUM_THREADS=1       # [not win]
    - export OMP_NUM_THREADS=1            # [not win]
    - setx MPLBACKEND "Agg"  # [win]
    - export MPLBACKEND=Agg  # [unix]
    - SKIMAGE_TEST_STRICT_WARNINGS=0 pytest --verbose --pyargs skimage -k "not ({{ tests_to_skip }})"  # [unix]
    - set "SKIMAGE_TEST_STRICT_WARNINGS=0" & pytest --verbose --pyargs skimage -k "not ({{ tests_to_skip }})"  # [win]

about:
  home: https://scikit-image.org/
  license: BSD-3-Clause AND MIT AND BSD-2-Clause
  license_family: Other
  license_file: LICENSE.txt
  summary: Image processing in Python.
  description: |
    scikit-image is a collection of algorithms for image processing.
    It is available free of charge and free of restriction.
    We pride ourselves on high-quality, peer-reviewed code,
    written by an active community of volunteers.
  dev_url: https://github.com/scikit-image/scikit-image
  doc_url: https://scikit-image.org/docs/stable/

extra:
  recipe-maintainers:
    - jakirkham
    - jni
    - msarahan
    - ocefpaf
    - soupault
    - hmaarrfk
    - emmanuelle
