{% set name = "scikit-image" %}
{% set version = "0.23.2" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/scikit-image/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: be1b8d38fb51b8076d829f682646f9fdb61f9936e43a8b775fb594c7c7930a88

build:
  number: 0
  skip: true  # [py<310]
  entry_points:
    - skivi = skimage.scripts.skivi:main

requirements:
  build:
    # pythran code needs clang-cl on windows
    - clang                 # [win]
    - lld                   # [win]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - python
    - cython >=3.0.4
    - numpy {{ numpy }}
    - packaging
    - pip
    - pythran
    - meson-python
    - lazy_loader >=0.3
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy', lower_bound='1.23') }}
    - scipy >=1.9
    - networkx >=2.8
    - pillow >=9.1
    - imageio >=2.33
    - tifffile >=2022.8.12
    - packaging >=21
    - lazy_loader >=0.4
    - _openmp_mutex  # [linux]
  run_constrained:
    - matplotlib-base >=3.6
    - pooch >=1.6.0
    - astropy >=5.0
    - scikit-learn >=1.1
    - pywavelets >=1.1.1
    - cloudpickle >=0.2.1
    - dask-core >=2021.1.0

{% set tests_to_skip = "_not_a_real_test" %}

# TODO: Report this upstream
# It seems that the apply_parallel tests can have relatively small errors,
# depending on underlying system; conda-forge has observed it on Windows, and
# Anaconda has observed it on Windows, macOS, and Linux.
{% set tests_to_skip = tests_to_skip + " or test_apply_parallel_rgb" %} # [osx and x86_64]

# https://github.com/scikit-image/scikit-image/issues/6865
{% set tests_to_skip = tests_to_skip + " or test_analytical_moments_calculation" %}

# https://github.com/scikit-image/scikit-image/issues/7061
{% set tests_to_skip = tests_to_skip + " or test_ellipse_parameter_stability" %}

# https://github.com/scikit-image/scikit-image/issues/6994
{% set tests_to_skip = tests_to_skip + " or test_imsave_roundtrip[shape1-uint16]" %}  # [linux and s390x]

# known to be broken on s390x: if platform.machine() == "s390x" and plugin == "pil" and fmt == "png"
{% set tests_to_skip = tests_to_skip + " or test_all_mono" %}          # [linux and s390x]

test:
  imports:
    - skimage
  source_files:
    - pyproject.toml
  requires:
    - pip
    - pooch >=1.6.0
    - asv
    - matplotlib-base
    - pywavelets
    - scikit-learn
    - numpydoc >=1.7
    - pytest >=7.0
    - pytest-cov >=2.11.0
    - pytest-localserver
    - astropy >=5.0
    - dask-core >=2021.1.0
    #- pytest-faulthandler
  commands:
    - pip check
    - python -c "import skimage; print(skimage.__version__)"
    - set OPENBLAS_NUM_THREADS=1          # [win]
    - set OMP_NUM_THREADS=1               # [win]
    - export OPENBLAS_NUM_THREADS=1       # [not win]
    - export OMP_NUM_THREADS=1            # [not win]
    - setx MPLBACKEND "Agg"  # [win]
    - export MPLBACKEND=Agg  # [unix]
    - SKIMAGE_TEST_STRICT_WARNINGS=0 pytest --verbose --pyargs skimage -k "not ({{ tests_to_skip }})"  # [unix]
    - set "SKIMAGE_TEST_STRICT_WARNINGS=0" & pytest --verbose --pyargs skimage -k "not ({{ tests_to_skip }})"  # [win]

about:
  home: https://scikit-image.org/
  license: BSD-3-Clause AND MIT AND BSD-2-Clause
  license_family: Other
  license_file: LICENSE.txt
  summary: Image processing in Python.
  description: |
    scikit-image is a collection of algorithms for image processing.
    It is available free of charge and free of restriction.
    We pride ourselves on high-quality, peer-reviewed code,
    written by an active community of volunteers.
  dev_url: https://github.com/scikit-image/scikit-image
  doc_url: https://scikit-image.org/docs/stable/

extra:
  recipe-maintainers:
    - jakirkham
    - jni
    - msarahan
    - ocefpaf
    - soupault
    - hmaarrfk
    - emmanuelle
