travis:
  secure:
    BINSTAR_TOKEN: aDvc1DYoCQpD/T8TB06/j72fANFmUWl7X2Z35sAwxy2vF5TAC1wn2pcanIjEJtaT/pwy4sPk+ZGT64c6BzyaB49evm8EFKUrZhGzjkSNDF/KVEQnGB2qNLe9okhtzKzLexE0FlZ7NnUte73v024NwuYG18TmF27o5Qsv2vxZHUzw+zFjrxqycatpG46qHEPU8xIf+Mf0Ip3m4nK0aBrTsPlkqxXbWjkS8kUOrTj06WmbhpgTKduwfIy5D8cVdMkjDsFs/FItpzQKn+2tBcSI6SfdTPgcAIFTHEtIRJfOqIx9X71A9u8qxvYlBbvz8BUMAMm1+dBbdfinkaJvuQzxfaIILouNCq3EveIx7DbdkBZKYEdP8lERJSxzeCAdPMoyffZ0+HZxx+yYJ7/su2t7AIRAOwmzKk6EoMBY8gEbG6C7IXfgbg96B7dchZwrwpP+o2MLUM6OHfPz5mawZPE/pxg2HabNz1ByUZ2wrlI70AmUS5ZnLvvoPivIZ6TvApi9tVjAhPk/kvpfxQddGLmLXtr8u/e5vEaT4FGGdX5Ia7m8VKgPNDkYc7YrqNhd0ocjt4WiIvJTI09pbb1VBrBtLy5LlLaYv4h2UcQONQA/Exgwi6O9ZxcLwMxPLKUCSM5jPMRVZ76fnWb0BSnHrbRZ3rliaKqK+QyyjBfV0oNghgQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
